### ISSUE TITLE
setApiKey is not a function

### ISSUE THREAD

**Issue by ZalgirisKaunas** [vijaypatoliya/pinterest-node-api#13]
/** Create oauth access token */
var refresh_token_payload = {
  grant_type: "refresh_token",
  refresh_token: "your refresh token",
};

var authorization_code_payload = {
  grant_type: "authorization_code",
  code: "code",
  redirect_uri: "redirect_uri",
};

/** Set pinterest clientId and clientSecret */
pinterest.setApiKey('clientId', 'clientSecret');

try {
  var response = await pinterest.oauth.createAccessToken(
    authorization_code_payload || refresh_token_payload
  );
} catch (error) {
  return;
}

it seems that setApiKey method is not defined and without this line it thorws authentication error code 2.

**Comment by ralyodio** [comment]
I'm also getting this.
