### ISSUE TITLE
Proper paging

### ISSUE THREAD

**Issue by atvorch** [vijaypatoliya/pinterest-node-api#5]
I want to retrieve all my pins.
Can you tell how to properly paging through pins using cursor or next url via your library?

Thanking you beforehand for your help!

**Comment by atvorch** [comment]
Figured out. Just added cursor property to the data object and passed to the getUserPins(data);

var data = { limit: 100, cursor: 'xxxx'};
pinterest.pins.getUserPins(data).then(() => {}); // it works

Thank you for contributing so much!

**Comment by vijaypatoliya** [comment]
@atvorch You’re very Welcome. Please Feel free to create Issue for any help!
