### ISSUE TITLE
createBoard didn't work...

### ISSUE THREAD

**Issue by doverradio** [vijaypatoliya/pinterest-node-api#6]
Hello, I am testing this library and tried to perform the `createBoard` call with some test name and description.

Result was an error:
```
[Error] {
  Type: 'pinterestAPIError',
  Code: 'GenericError',
  Message: 'Invalid response received from the pinterest API',
  StatusCode: 404
}
```

My code:
```
var pinterest = require('pinterest-node-api')(process.env.PINTEREST_USER_TOKEN)

exports.createBoard = async ( req, res ) =>
{
    let a = {}
    try 
    {
        let { name, description } = req.body
        var data = {
            name,
            description
          }; 
        var response = await pinterest.boards.createBoard(data);
        res.json( response )
    } catch ( e ) {
        console.log( `createBoard e: `, e )
        res.status( 400 ).json( { error: e, report: a } )
    }
}

```

I'm using express.js for by backend.

How can I get a successful `createBoard` call?  What was done wrong?  

Please let me know the correct way. 

Thank you.

**Comment by vijaypatoliya** [comment]
Hey @doverradio 
Thanks for providing all details. We will investigate the issue and get back ASAP. Meanwhile, just make sure your Pinterest account has not had any blockers.

**Comment by vijaypatoliya** [comment]
Hello @doverradio 
Thanks for your patience. The older Pinterest API will be deprecated shortly. I have upgraded to v5 latest API with full support and all methods. Kindly download the latest version. Thanks
